import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { HomeScreen } from "../../components/home-screen";
import { ROLES, ROLE_BY_ID } from "../../config/roles";

/* Six addresses for the six roles, and the reason they exist is the share.
 *
 * "Which of the six are you?" is a link a person sends for fun. Whiff's old
 * link preview said, on the recipient's screen, that the sender is trying to
 * make friends — a confession — and nobody forwards a confession. A role card
 * says something about the sender they are happy to have said, and it asks
 * the recipient a question instead of making a claim about them.
 *
 * The page itself is the home screen with the explorer opened on that role.
 * Not a microsite about Spark: the point of arriving is to press the other
 * six tabs and end up at the ask, which is exactly what the home page does.
 *
 * They are indexable on purpose. "Which of the six are you" and every role
 * name are queries with no confession in them either, and six pages of real,
 * distinct copy is the only body text this one-screen site has outside /blog.
 *
 * Statically generated — `generateStaticParams` returns all six and there is
 * no other value the segment can take, so an unknown role 404s at build. */
export function generateStaticParams() {
  return ROLES.map((role) => ({ role: role.id }));
}

export const dynamicParams = false;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ role: string }>;
}): Promise<Metadata> {
  const { role: id } = await params;
  const role = ROLE_BY_ID.get(id);
  if (!role) return {};

  // The root layout's template appends " · whiff", so the title reads
  // "Spark: spontaneous, gets things moving · whiff" in a tab and in a result.
  const title = `${role.name}: ${role.tagline.toLowerCase()}`;
  // Two sentences of the role, then the question — the question is what makes
  // the preview worth opening, so it survives every snippet truncation by
  // sitting inside the first 155 characters wherever the role copy is short.
  const description = `${role.inCircle} Which of the six are you? whiff seats circles of four by how you answer, not how you look.`;

  return {
    title,
    description,
    alternates: { canonical: `/roles/${role.id}` },
    openGraph: {
      type: "article",
      url: `/roles/${role.id}`,
      title,
      description,
      // og:image is generated by the colocated opengraph-image.tsx
    },
    twitter: { card: "summary_large_image", title, description },
  };
}

export default async function RolePage({
  params,
}: {
  params: Promise<{ role: string }>;
}) {
  const { role: id } = await params;
  if (!ROLE_BY_ID.has(id)) notFound();

  return <HomeScreen initialRole={id} />;
}
