import type { Metadata, Viewport } from "next";
import { Caveat, Fredoka, Nunito } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { AmbientBackground } from "./components/ambient-background";
import { LIVE_MARKETS, SITE_NAME, SITE_URL } from "./config/site";
import { PROMISE } from "./seo-content";

// Fredoka — the display face: wordmark, headings, the emotional lines.
const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-fredoka",
  display: "swap",
});

// Caveat — the handwriting. Whiff's voice, and the app's rule travels with it:
// exactly one handwritten line per screen.
const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-caveat",
  display: "swap",
});

// Nunito — the body: everything you read at length.
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-nunito",
  display: "swap",
});

/* The home page's own <title>, and the line that travels.
 *
 * It used to lead with the job a searcher is doing — "make real friends
 * through activities, not profiles" — which is good for a query and bad for
 * everything else, because a title is not read in a results page half the
 * time. It is read in a text message. Paste the old link into a group chat
 * and the preview said, on the recipient's screen, that the person who sent
 * it is trying to make friends. That is a confession, and it is enough to
 * stop somebody sharing at all.
 *
 * The structural line has no confession in it, and it is more distinctive
 * anyway: nobody else can say "same four people". The cost is real and worth
 * naming — "make friends" is gone from the highest-weighted tag on the site,
 * so the intent match now rests on the H1, /blog and /llms.txt.
 *
 * A colon, not an em dash: whiff's copy does not use them. */
const TITLE = "whiff: six activities. twelve weeks. same four people.";

/* Under 160 characters. The promise, then the mechanism stated as the thing
 * that makes it not a dating app — "how you answer, not how you look" does
 * the disqualifying work that the words "not a dating app" used to do, in a
 * sentence somebody would actually repeat. It closes on where whiff is, which
 * is the only fact in it that can go stale, so it renders from the market
 * data rather than being typed here. */
const DESCRIPTION = `${PROMISE} Circles of four, seated by how you answer, not how you look. Starting in ${LIVE_MARKETS[0].region}.`;

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    // The home page needs a descriptive title, not a bare wordmark: "whiff" on
    // its own gives a search engine nothing to match a query against, and it is
    // the single highest-weight on-page signal there is. Sub-pages still read
    // "Privacy Policy · whiff".
    default: TITLE,
    template: "%s · whiff",
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  generator: "Next.js",
  authors: [{ name: "whiff", url: SITE_URL }],
  creator: "whiff",
  publisher: "whiff",
  category: "social",
  referrer: "origin-when-cross-origin",
  formatDetection: { email: false, address: false, telephone: false },
  // No `keywords`: Google has ignored the meta keywords tag for well over a
  // decade, and a long list of near-duplicate phrases is the exact pattern that
  // reads as stuffing. Intent is targeted with titles, headings and body copy.
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: TITLE,
    description: DESCRIPTION,
    locale: "en_US",
    // og:image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // twitter:image is generated by app/twitter-image.tsx
  },
  manifest: "/manifest.webmanifest",
  verification: {
    google: "7HSBXXr_uXXPWc5UdbeR0Zh8PpUA-KnGxFr5WfqP_6o",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
};

// Structured data now lives per page (app/lib/structured-data.ts), so every URL
// emits one @graph containing the Organization plus whatever that page is
// actually about — FAQPage, HowTo, a city Service, and so on.

/* The CTA split, assigned before the first paint.
 *
 * It runs synchronously as the first thing in <body>, which is what makes it
 * safe: the attribute is on <html> before the button below it is parsed, so
 * nobody sees "Get your invite" turn into "Take your seat". The variant is
 * kept in localStorage so a returning visitor stays in the arm they were
 * counted in — a split that reshuffles per visit measures nothing.
 *
 * Wrapped in try/catch because localStorage throws outright in some privacy
 * modes. When it does, no attribute is set, the CSS default wins, and that
 * visitor is simply not in the experiment. */
const CTA_SPLIT = `(function(){try{var k="whiff-cta",v=localStorage.getItem(k);if(v!=="begin"&&v!=="seat"){v=Math.random()<0.5?"begin":"seat";localStorage.setItem(k,v)}document.documentElement.dataset.cta=v}catch(e){}})()`;

export const viewport: Viewport = {
  themeColor: "#FBF8F5",
  width: "device-width",
  initialScale: 1,
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      suppressHydrationWarning
      className={`${fredoka.variable} ${nunito.variable} ${caveat.variable} h-full antialiased`}
    >
      {/* suppressHydrationWarning: browser extensions (password managers,
          Grammarly, ad blockers) commonly inject nodes/attributes into <body>
          before React hydrates. That mismatch is benign; this quiets it. */}
      <body suppressHydrationWarning className="min-h-[100svh] flex flex-col">
        <script dangerouslySetInnerHTML={{ __html: CTA_SPLIT }} />
        {/* Keyboard and screen-reader users land on the header's dialog buttons
            first on every page; this gives them one tab to skip past it. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[200] focus:rounded-full focus:bg-ground-lift focus:px-5 focus:py-2.5 focus:font-display focus:text-sm focus:font-semibold focus:text-ink focus:shadow-lg"
        >
          Skip to content
        </a>
        <AmbientBackground />
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
