import type { Metadata, Viewport } from "next";
import { Caveat, Fredoka, Nunito } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { AmbientBackground } from "./components/ambient-background";
import { SITE_NAME, SITE_URL } from "./config/site";
import { PROMISE } from "./seo-content";

// Fredoka — the display face: wordmark, headings, the emotional lines.
const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-fredoka",
  display: "swap",
});

// Caveat — the handwriting. Whiff's voice, and the app's rule travels with it:
// exactly one handwritten line per screen.
const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-caveat",
  display: "swap",
});

// Nunito — the body: everything you read at length.
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-nunito",
  display: "swap",
});

// The home page's own <title>. Leads with the job the searcher is trying to do
// ("make friends") rather than the brand, because nobody searches for a brand
// they have never heard of — then the differentiator, then the disqualifier.
const TITLE = "whiff: make real friends through activities, not profiles";

// Under 160 characters, opens with the promise, closes with the disqualifier so
// no snippet can imply dating.
const DESCRIPTION =
  `${PROMISE} Activity-first friend circles of four who keep meeting up. No profiles, no swiping. Not a dating app.`;

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    // The home page needs a descriptive title, not a bare wordmark: "whiff" on
    // its own gives a search engine nothing to match a query against, and it is
    // the single highest-weight on-page signal there is. Sub-pages still read
    // "Privacy Policy · whiff".
    default: TITLE,
    template: "%s · whiff",
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  generator: "Next.js",
  authors: [{ name: "whiff", url: SITE_URL }],
  creator: "whiff",
  publisher: "whiff",
  category: "social",
  referrer: "origin-when-cross-origin",
  formatDetection: { email: false, address: false, telephone: false },
  // No `keywords`: Google has ignored the meta keywords tag for well over a
  // decade, and a long list of near-duplicate phrases is the exact pattern that
  // reads as stuffing. Intent is targeted with titles, headings and body copy.
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: TITLE,
    description: DESCRIPTION,
    locale: "en_US",
    // og:image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // twitter:image is generated by app/twitter-image.tsx
  },
  manifest: "/manifest.webmanifest",
  verification: {
    google: "7HSBXXr_uXXPWc5UdbeR0Zh8PpUA-KnGxFr5WfqP_6o",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
};

// Structured data now lives per page (app/lib/structured-data.ts), so every URL
// emits one @graph containing the Organization plus whatever that page is
// actually about — FAQPage, HowTo, a city Service, and so on.

export const viewport: Viewport = {
  themeColor: "#FBF8F5",
  width: "device-width",
  initialScale: 1,
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      suppressHydrationWarning
      className={`${fredoka.variable} ${nunito.variable} ${caveat.variable} h-full antialiased`}
    >
      {/* suppressHydrationWarning: browser extensions (password managers,
          Grammarly, ad blockers) commonly inject nodes/attributes into <body>
          before React hydrates. That mismatch is benign; this quiets it. */}
      <body suppressHydrationWarning className="min-h-[100svh] flex flex-col">
        {/* Keyboard and screen-reader users land on the header's dialog buttons
            first on every page; this gives them one tab to skip past it. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[200] focus:rounded-full focus:bg-ground-lift focus:px-5 focus:py-2.5 focus:font-display focus:text-sm focus:font-semibold focus:text-ink focus:shadow-lg"
        >
          Skip to content
        </a>
        <AmbientBackground />
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
