import type { Metadata, Viewport } from "next";
import { Geist, Fraunces, Caveat } from "next/font/google";
import "./globals.css";
import { AmbientBackground } from "./components/ambient-background";
import { ScrollProgress } from "./components/scroll-progress";
import { FAQ } from "./seo-content";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-fraunces",
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-caveat",
});

const SITE_URL = "https://whiff-ai.com";
const SITE_NAME = "whiff";
const TITLE = "whiff: AI-curated rooms for real-life connection";
const DESCRIPTION =
  "whiff is an AI for real-life connection. Meet friends, community, run mates, or love without profiles or swiping, with space for neurodivergent adults.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: "%s · whiff",
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  generator: "Next.js",
  keywords: [
    "whiff",
    "discover whiff",
    "AI for real-life connection",
    "AI matchmaker",
    "AI that finds friends",
    "dating app fatigue",
    "dating app burnout",
    "make friends as an adult",
    "meet people without swiping",
    "alternative to dating apps",
    "no swiping no profiles",
    "find your community",
    "find a run mate",
    "meet people 25 and up",
    "dating app for autistic adults",
    "making friends as an autistic adult",
    "app for people on the spectrum",
    "neurodivergent friendship app",
    "autism friendly way to meet people",
    "meet people without small talk",
    "ADHD friendly dating app",
    "social anxiety friendly dating",
  ],
  authors: [{ name: "whiff", url: SITE_URL }],
  creator: "whiff",
  publisher: "whiff",
  category: "social",
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: SITE_URL,
  },
  verification: {
    google: "7HSBXXr_uXXPWc5UdbeR0Zh8PpUA-KnGxFr5WfqP_6o",
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: TITLE,
    description: DESCRIPTION,
    locale: "en_US",
    // og:image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // twitter:image is generated by app/twitter-image.tsx
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/whiff-icon.svg", type: "image/svg+xml" },
    ],
    apple: [{ url: "/whiff-icon.png", sizes: "512x512", type: "image/png" }],
  },
  manifest: "/manifest.webmanifest",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f2ebe0" },
    { media: "(prefers-color-scheme: dark)", color: "#2e2723" },
  ],
  width: "device-width",
  initialScale: 1,
  colorScheme: "light",
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${SITE_URL}#organization`,
      name: SITE_NAME,
      url: SITE_URL,
      logo: `${SITE_URL}/whiff-icon.png`,
      description: DESCRIPTION,
      slogan: "AI-curated rooms for real-life connection.",
      knowsAbout: [
        "real-life connection",
        "making friends as an adult",
        "alternative to dating apps",
        "meeting people without swiping or profiles",
        "connection for autistic and neurodivergent adults",
        "making friends as an autistic adult",
        "low-pressure ways to meet people without small talk",
      ],
      sameAs: [
        "https://www.instagram.com/discover_whiff/",
        "https://www.tiktok.com/@discover_whiff",
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}#website`,
      url: SITE_URL,
      name: SITE_NAME,
      description: DESCRIPTION,
      publisher: { "@id": `${SITE_URL}#organization` },
      inLanguage: "en-US",
    },
    {
      "@type": "Service",
      "@id": `${SITE_URL}#service`,
      name: "whiff",
      serviceType: "AI companion and matchmaking for real-life connection",
      description:
        "An AI you talk to that learns who you are, talks to other people's AI, and introduces you to the people who should be in your life: friends, a run mate, sometimes love, or a whole community. No profiles, no swiping, and no small talk to perform, which makes it a natural fit for autistic and neurodivergent adults. For adults 25 and up.",
      url: SITE_URL,
      provider: { "@id": `${SITE_URL}#organization` },
      areaServed: "Worldwide",
      audience: {
        "@type": "Audience",
        audienceType:
          "Adults 25 and up seeking genuine real-life connection, including autistic and neurodivergent people and anyone who finds dating apps, profiles, and small talk draining.",
      },
    },
    {
      "@type": "FAQPage",
      "@id": `${SITE_URL}#faq`,
      mainEntity: FAQ.map(({ q, a }) => ({
        "@type": "Question",
        name: q,
        acceptedAnswer: { "@type": "Answer", text: a },
      })),
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${geist.variable} ${fraunces.variable} ${caveat.variable} h-full antialiased`}
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-[100svh] flex flex-col">
        <ScrollProgress />
        <AmbientBackground />
        {children}
      </body>
    </html>
  );
}
