/** Visible copy, metadata and Article schema all draw from this public content. */
export const GUIDE_UPDATED = "2026-09-18";
export const HALL_PAPER = "https://journals.sagepub.com/doi/full/10.1177/0265407518761225";
export const HALL_SUMMARY = "https://news.ku.edu/news/article/2018/03/06/study-reveals-number-hours-it-takes-make-friend";
export type GuideSource = { label: string; href: string };
export type GuideSection = { id: string; title: string; paragraphs: string[]; sources?: GuideSource[] };
export type Guide = { slug: string; collection: "mn" | "blog"; title: string; shortTitle: string; description: string; intro: string; label: string; takeaway: string; sections: GuideSection[] };
const lakes = { label: "Minneapolis Park Board: Chain of Lakes", href: "https://www.minneapolisparks.org/parks-destinations/parks-lakes/minneapolis_chain_of_lakes_regional_park/" };
const library = { label: "Hennepin County Library: books, events and book clubs", href: "https://www.hclib.org/programs/books-reading" };
const saintPaulLibrary = { label: "Saint Paul Public Library: adult programs", href: "https://sppl.org/blogs/post/step-out-of-your-bubble-fun-free-programs-for-adults-at-the-library/" };
const volunteer = { label: "Saint Paul Parks & Recreation: volunteer opportunities", href: "https://www.stpaul.gov/departments/parks-and-recreation/volunteer" };
const parks = { label: "Minnesota DNR: ParkFinder", href: "https://www.dnr.state.mn.us/parkfinder/index.html" };
const mia = { label: "Minneapolis Institute of Art: plan a visit", href: "https://new.artsmia.org/visit" };
export const GUIDES: Guide[] = [
  {
    slug: "moving-to-minnesota", collection: "mn", label: "01 / A NEW CHAPTER", shortTitle: "Moving to Minnesota",
    title: "Moving to Minnesota? Build a life beyond the moving boxes.",
    description: "A practical first-month social plan for moving to Minnesota: find familiar places, recurring activities and potential friends in Minneapolis and Saint Paul.",
    intro: "You can finish unpacking and still feel new. A social routine takes a different kind of settling in: finding places you like, making a small plan, and giving the same people another chance to become familiar.",
    takeaway: "Your first-month goal: one familiar place, one recurring activity, and one second invitation.",
    sections: [
      { id: "start-nearby", title: "Start with your actual week", paragraphs: ["Minnesota is bigger than the Twin Cities. A routine that works in Minneapolis may be impractical in Duluth or a smaller town. Start with the distance you can comfortably travel after work, your budget, and the days you can reliably leave home. Build from that radius rather than a statewide bucket list.", "If you are moving to Minneapolis or Saint Paul, pick a nearby place where you can return without a production: a library, a park route, or a community space. Visit at roughly the same time. The first win is learning the place well enough that going back takes less effort."] },
      { id: "week-one", title: "Week one: make one place familiar", paragraphs: ["Keep this week small. Take a daylight walk, learn the route home, and find an indoor alternative. In Minneapolis, the Chain of Lakes is one possible starting point; choose a manageable section rather than committing to a long loop. Check the park information for facilities and conditions before leaving.", "You do not need to turn every outing into a networking exercise. Notice what you enjoy enough to repeat. A place that fits your ordinary life is more useful for building a routine than an impressive outing you will never make time for again."], sources: [lakes] },
      { id: "week-two", title: "Week two: choose something that meets again", paragraphs: ["Look for a recurring book group, class, volunteer role, or activity with a clear next meeting. Hennepin County Library lists reading programs and book clubs; Saint Paul Public Library also has adult programs. Check each listing for location, registration and frequency rather than assuming every event repeats.", "A useful question for the organizer is: ‘Is this a group people come back to, and is it okay to join on my own?’ Pick something you want to do even if the first conversation is short. That gives you a reason to return before you feel connected."], sources: [library, saintPaulLibrary] },
      { id: "weeks-three-four", title: "Weeks three and four: make the next plan smaller", paragraphs: ["Return to the same activity. Learn a name, ask a follow-up question, and offer one specific invitation if the conversation feels mutual: ‘I’m getting coffee after next week’s session. Want to join?’ A clear time and a simple plan are easier to answer than ‘We should hang out.’", "Keep in touch with old friends while you do this. A new city does not need to replace your whole social life in thirty days. If a group feels wrong, try another; if it feels simply unfamiliar, consider giving it a second visit. You are looking for a sustainable rhythm, not a deadline for belonging."] },
      { id: "whiff", title: "Where Whiff fits", paragraphs: ["Whiff is being built for platonic friendship through the same four people meeting for six planned activities over twelve weeks. Its first circles are forming in Minneapolis–Saint Paul; this is not a claim of statewide availability. App Store and Google Play links are coming soon. In the meantime, this plan works with a class, a neighborhood group, or a small circle you organize yourself."] },
    ],
  },
  {
    slug: "things-to-do", collection: "mn", label: "02 / OUT OF THE HOUSE", shortTitle: "Things to do in Minnesota",
    title: "Things to do in Minnesota that leave room for conversation.",
    description: "Explore Minnesota with potential friends: Twin Cities walks, art, library activities and state-park day trips, with practical planning tips and official sources.",
    intro: "An outing does not need to be spectacular to be worth doing together. Pick something with a shared focus, enough space to talk, and a next visit you could actually put in the calendar.",
    takeaway: "Choose the plan everyone can comfortably repeat, then agree on the next one before you leave.",
    sections: [
      { id: "lakes", title: "A short lake walk in Minneapolis", paragraphs: ["The Chain of Lakes is a concrete place to begin a Twin Cities outing. Choose a meeting point people can find, a short out-and-back route, and an indoor backup. A walk lets conversation have pauses; you can look at the water without needing to fill every second.", "For a first meet, set aside around an hour as your own planning estimate, not a promise about any trail. Make drinks optional and discuss transport, parking, surfaces and accessibility in advance. The Park Board’s information is the place to check facilities and current notices."], sources: [lakes] },
      { id: "art", title: "An indoor art afternoon", paragraphs: ["The Minneapolis Institute of Art offers free general admission, while some special exhibitions or events may have a separate charge. Its visit page has current details. Choose a few galleries instead of trying to finish the museum, then let each person pick one work to talk about.", "A suggested plan is sixty to ninety minutes, with a break whenever the group wants one. You do not need art knowledge or a clever interpretation. ‘Which one would you take home?’ is enough. Agree on any paid extras before booking, so nobody has to explain their budget at the entrance."], sources: [mia] },
      { id: "library", title: "A library activity you can return to", paragraphs: ["Hennepin County Library’s reading resources and Saint Paul Public Library’s adult programs are starting points for book groups and other shared interests. Follow through to the individual listing for age guidance, registration and the next date. A library program can be an outing in its own right, not just a place to find another event.", "If you want to meet people, favor a format that gives participants something to discuss or do together. A quiet lecture may be enjoyable but need a separate conversation afterward. Ask whether the same group meets again; that detail matters more than the size of the room."], sources: [library, saintPaulLibrary] },
      { id: "beyond-the-metro", title: "A Minnesota state-park day trip", paragraphs: ["For a longer outing beyond the city, use Minnesota DNR’s ParkFinder to choose a park that fits the group’s interests and travel range. Check the individual park page for permits, closures, trail information and available facilities. Do not assume a summer plan has the same access or conditions in winter.", "Treat a day trip as a later plan once everyone is comfortable with the time and transport commitment. Agree on driving, fuel, food, weather alternatives and how long you will stay. You can still share an outdoor afternoon without a strenuous hike or expensive equipment."], sources: [parks] },
      { id: "make-it-repeatable", title: "The part after the activity", paragraphs: ["These are independent suggestions, not booked Whiff outings or venue partnerships. Times above are planning ideas; check official pages for opening hours and actual costs. Minnesota weather and everyone’s energy may change the plan, and a simpler backup is useful.", "Before leaving, try one question: ‘Would we want to do this again, or try something similar next week?’ Whiff’s first Twin Cities circles are forming around a related idea: six activities with the same four people. You can begin with that habit yourself, even while the app-store links are coming soon."] },
    ],
  },
  {
    slug: "make-friends", collection: "mn", label: "03 / THE SAME FACES", shortTitle: "Make friends in Minnesota",
    title: "How to make friends in Minnesota as an adult.",
    description: "Practical ways to make platonic friends in Minnesota, from recurring library groups and volunteering to small activity circles in Minneapolis and Saint Paul.",
    intro: "Moving here is one reason to want new friends. So is working from home, watching friends move away, or realizing your week has become work and errands. You can start building something without starting your whole life over.",
    takeaway: "Find a shared reason to show up. Return. Make one specific invitation. Let closeness take its own pace.",
    sections: [
      { id: "choose-a-pattern", title: "Look for a pattern, not just an event", paragraphs: ["A big event can be fun, but it does not always tell you how to see someone again. When comparing activities, ask three things: will people return, is there time to talk, and can I realistically keep attending? A small recurring group can fit those needs better than a busy social calendar.", "There is no single Minnesota personality you need to crack. People differ, existing friendships take time, and schedules matter. Choose a setting that suits you rather than treating a quiet first conversation as a verdict on the whole state or on your ability to connect."] },
      { id: "shared-interests", title: "Use an interest as the introduction", paragraphs: ["Book groups give you something to talk about before you know anyone’s life story. Hennepin County Library’s reading pages and Saint Paul Public Library’s adult programs are useful starting points. Look at the actual listing for registration, location and whether it is recurring.", "The same principle can work with a class or a community activity near you. Pick a subject you actually enjoy, and check whether beginners can join. You do not have to be interesting on command when everyone has a task, a book, or a small thing to learn together."], sources: [library, saintPaulLibrary] },
      { id: "volunteer", title: "Do something useful alongside other people", paragraphs: ["Saint Paul Parks & Recreation lists volunteer opportunities. Start with work you would value doing even if it does not produce a friendship. Ask the organizer about the commitment, orientation, accessibility and whether volunteers work together or independently.", "A repeat shift may create familiarity, but volunteering is also a responsibility to the people or place being served. Choose a role you can reliably honor. If the available task is solitary, it may still be worthwhile; just do not make it your only plan for meeting people."], sources: [volunteer] },
      { id: "follow-up", title: "Make the second invitation easy to answer", paragraphs: ["After a good conversation, name a specific, low-pressure plan: ‘I’m taking a short walk before the next session. Would you like to come?’ Include a time and place, and leave room for a no. Mutual interest matters more than persistence.", "If someone cannot come, an offered alternative is useful information. If invitations repeatedly go unanswered, give them space and invest elsewhere. This is not a competition to turn every acquaintance into a close friend. A friendly familiar face can be a good part of your week too."] },
      { id: "small-circle", title: "Build a small circle, with or without an app", paragraphs: ["You can invite two or three people to a recurring walk, library outing, or casual activity. Keep costs clear and make the next date explicit. Agree that the purpose is platonic friendship so nobody needs to guess whether the plan is a date.", "Whiff is one option being built around that consistency: four people, six planned activities, twelve weeks. The first circles are forming in Minneapolis–Saint Paul, with store links coming soon. It is not a dating app, and it cannot guarantee chemistry. Classes, volunteering and self-organized groups remain useful routes in their own right."] },
      { id: "give-it-time", title: "Measure effort kindly", paragraphs: ["For the first month, count the plans you followed through on and the places you felt comfortable returning to. Do not grade yourself by whether you have a best friend yet. Research on friendship and time is helpful context, not a stopwatch or a promise. A routine makes room for connection; the people still get to decide what grows."] },
    ],
  },
  {
    slug: "how-long-does-it-take-to-make-friends", collection: "blog", label: "FIELD NOTES / THE RESEARCH", shortTitle: "The time friendship takes",
    title: "How long does it take to make friends? What Hall’s research says.",
    description: "Jeffrey A. Hall’s friendship-hours research, explained: roughly 50, 90 and over 200 total hours, what the studies measured, and what they do not promise.",
    intro: "A good first conversation can happen in minutes. Becoming part of each other’s lives usually takes more opportunities than that. Jeffrey A. Hall studied how time together relates to friendship, and the findings offer useful context for building a social routine.",
    takeaway: "Give friendship opportunities to grow. The hours are estimates, not a deadline, a guarantee, or a score.",
    sections: [
      { id: "study", title: "The paper behind the familiar numbers", paragraphs: ["Hall’s paper, “How many hours does it take to make a friend?”, first appeared online in 2018 and was published in the Journal of Social and Personal Relationships, volume 36, issue 4, in 2019. It studied 355 adults who had recently relocated and followed 112 first-year students over nine weeks.", "The University of Kansas summary describes estimates of about 50 total hours to move toward casual friendship, about 90 toward friendship, and more than 200 toward close friendship. Those are approximate totals, not 50 hours plus another 90 plus another 200. They describe patterns in the studies, not universal milestones."], sources: [{ label: "Read Jeffrey A. Hall’s original paper (DOI: 10.1177/0265407518761225)", href: HALL_PAPER }, { label: "University of Kansas: study explanation", href: HALL_SUMMARY }] },
      { id: "kind-of-time", title: "Being in the same room is not the whole story", paragraphs: ["Hall’s findings connect shared leisure time and some everyday conversation with greater closeness. Simply accumulating hours around someone at work does not mean the relationship will develop in the same way. The kind of contact matters alongside the amount.", "Our practical reading is to make room for interaction people actually choose: a walk after a class, a shared meal, or another round of a game. These examples are suggestions, not activities tested or prescribed by the paper. A comfortable plan gives conversation somewhere to happen without requiring instant intimacy."], sources: [{ label: "Hall: methods, findings and discussion", href: HALL_PAPER }] },
      { id: "limits", title: "What the numbers cannot tell you", paragraphs: ["The studies rely on people’s reports of their time and relationships. They are observational, so an association between hours and closeness does not establish that adding hours alone causes friendship. The groups studied also cannot represent every age, culture, situation or kind of relationship.", "Closeness does not follow an identical schedule for everyone. Do not use an estimated threshold to pressure yourself or another person, or assume you are owed a friendship because you spent time together. Mutual interest, how you treat one another, and whether you want to return remain important parts of your own decision."] },
      { id: "practice", title: "Put the next meeting in reach", paragraphs: ["Try choosing one activity you can repeat without stretching your budget or schedule. A smaller plan you can keep is often a better personal experiment than an ambitious social overhaul. After the first visit, decide whether you liked the setting enough to return, even if you only learned one name.", "If you enjoyed talking to someone, offer a concrete follow-up rather than a vague promise to stay in touch. Leave room for them to decline. Over time, notice whether the effort is mutual and whether being together becomes more comfortable. You are building a relationship, not logging a training target."] },
      { id: "whiff", title: "Why we care about this at Whiff", paragraphs: ["Whiff is being built around repeated contact: the same four people, six planned activities, twelve weeks. Hall’s research is context for that design choice; it is not a study of Whiff, an endorsement, or proof that our approach works.", "Six outings do not imply 200 hours together and do not guarantee close friends. The aim is to make the next meeting easier to arrange, leaving the friendship itself to the people. Our first circles are forming in Minneapolis–Saint Paul, and the store links are coming soon."] },
    ],
  },
];
export const MINNESOTA_GUIDES = GUIDES.filter((guide) => guide.collection === "mn");
export function guidePath(guide: Guide) { return `/${guide.collection}/${guide.slug}`; }
export function findGuide(collection: Guide["collection"], slug: string) { return GUIDES.find((guide) => guide.collection === collection && guide.slug === slug); }
